import type {
  ActivityEntry,
  CrmMetrics,
  CustomerAccount,
  FollowUpTask,
  Opportunity,
  PipelineStageSummary,
} from "@/lib/contracts";

export const crmCustomers: CustomerAccount[] = [
  {
    id: "acct-aurora",
    name: "Aurora Retail",
    segment: "Enterprise",
    industry: "新零售",
    owner: "Lynn",
    contactName: "张可",
    role: "数字化平台主管",
    arr: 420000,
    stage: "商务谈判",
    healthScore: 61,
    lastContactAt: "2026-04-25",
    nextAction: "确认试点门店上线范围",
    priority: "urgent",
  },
  {
    id: "acct-helix",
    name: "Helix Bio",
    segment: "Mid-Market",
    industry: "生物科技",
    owner: "Mika",
    contactName: "李睿",
    role: "IT 负责人",
    arr: 180000,
    stage: "方案沟通",
    healthScore: 86,
    lastContactAt: "2026-04-26",
    nextAction: "发送合规版实施计划",
    priority: "key",
  },
  {
    id: "acct-lattice",
    name: "Lattice Cloud",
    segment: "Enterprise",
    industry: "云基础设施",
    owner: "Alec",
    contactName: "周洋",
    role: "采购总监",
    arr: 680000,
    stage: "签约推进",
    healthScore: 79,
    lastContactAt: "2026-04-24",
    nextAction: "法务条款最终确认",
    priority: "key",
  },
  {
    id: "acct-ripple",
    name: "Ripple Logistics",
    segment: "Mid-Market",
    industry: "物流",
    owner: "Lynn",
    contactName: "韩松",
    role: "运营副总裁",
    arr: 240000,
    stage: "线索初筛",
    healthScore: 74,
    lastContactAt: "2026-04-23",
    nextAction: "安排首次需求访谈",
    priority: "normal",
  },
  {
    id: "acct-summit",
    name: "Summit Motors",
    segment: "Enterprise",
    industry: "汽车制造",
    owner: "Mika",
    contactName: "郑宁",
    role: "售后数字化负责人",
    arr: 530000,
    stage: "商务谈判",
    healthScore: 48,
    lastContactAt: "2026-04-18",
    nextAction: "升级至 VP 级续约沟通",
    priority: "urgent",
  },
];

export const crmFollowUps: FollowUpTask[] = [
  {
    id: "task-001",
    title: "推进 Aurora Retail 合同折扣确认",
    type: "商务复盘",
    accountId: "acct-aurora",
    accountName: "Aurora Retail",
    owner: "Lynn",
    dueDate: "2026-04-27",
    priority: "urgent",
    riskLevel: "high",
    nextStep: "锁定采购审批窗口",
    notes: "客户要求将试点门店范围写入补充协议，需要销售与交付联合确认。"
  },
  {
    id: "task-002",
    title: "为 Helix Bio 演示审计追踪能力",
    type: "方案演示",
    accountId: "acct-helix",
    accountName: "Helix Bio",
    owner: "Mika",
    dueDate: "2026-04-27",
    priority: "key",
    riskLevel: "low",
    nextStep: "推动 PoC 范围确认",
    notes: "重点展示权限隔离、审计日志和实验记录追溯能力。"
  },
  {
    id: "task-003",
    title: "跟进 Lattice Cloud 法务条款红线",
    type: "电话跟进",
    accountId: "acct-lattice",
    accountName: "Lattice Cloud",
    owner: "Alec",
    dueDate: "2026-04-28",
    priority: "key",
    riskLevel: "medium",
    nextStep: "确认签约时间表",
    notes: "对方希望缩短数据保留条款，法务已给出替代版本，需要电话同步。"
  },
  {
    id: "task-004",
    title: "挽回 Summit Motors 续约意向",
    type: "续约沟通",
    accountId: "acct-summit",
    accountName: "Summit Motors",
    owner: "Mika",
    dueDate: "2026-04-27",
    priority: "urgent",
    riskLevel: "high",
    nextStep: "拉齐 VP 级业务复盘",
    notes: "已连续 9 天无正向反馈，需准备价值复盘与新报价策略。"
  },
];

export const crmOpportunities: Opportunity[] = [
  {
    id: "opp-aurora-expand",
    name: "门店运营扩容包",
    accountId: "acct-aurora",
    accountName: "Aurora Retail",
    amount: 320000,
    owner: "Lynn",
    stage: "商务谈判",
    probability: 62,
    expectedCloseDate: "2026-05-06",
  },
  {
    id: "opp-helix-poc",
    name: "合规实验室 PoC",
    accountId: "acct-helix",
    accountName: "Helix Bio",
    amount: 180000,
    owner: "Mika",
    stage: "方案沟通",
    probability: 45,
    expectedCloseDate: "2026-05-15",
  },
  {
    id: "opp-lattice-master",
    name: "集团主框架协议",
    accountId: "acct-lattice",
    accountName: "Lattice Cloud",
    amount: 680000,
    owner: "Alec",
    stage: "签约推进",
    probability: 84,
    expectedCloseDate: "2026-04-30",
  },
  {
    id: "opp-ripple-new",
    name: "物流调度数字化立项",
    accountId: "acct-ripple",
    accountName: "Ripple Logistics",
    amount: 240000,
    owner: "Lynn",
    stage: "线索初筛",
    probability: 28,
    expectedCloseDate: "2026-05-22",
  },
  {
    id: "opp-summit-renewal",
    name: "售后体系续约与扩模",
    accountId: "acct-summit",
    accountName: "Summit Motors",
    amount: 530000,
    owner: "Mika",
    stage: "商务谈判",
    probability: 38,
    expectedCloseDate: "2026-05-12",
  },
];

export const crmActivityFeed: ActivityEntry[] = [
  {
    id: "act-001",
    title: "Aurora Retail 商务边界收敛",
    kind: "会议结论",
    accountId: "acct-aurora",
    accountName: "Aurora Retail",
    owner: "Lynn",
    createdAt: "2026-04-26",
    summary: "客户接受按门店分批上线，但要求第一阶段交付 SLA 单独入合同附件。"
  },
  {
    id: "act-002",
    title: "Helix Bio 完成第一次解决方案走查",
    kind: "电话纪要",
    accountId: "acct-helix",
    accountName: "Helix Bio",
    owner: "Mika",
    createdAt: "2026-04-26",
    summary: "实验室负责人明确关注审计追踪与审批链可视化，PoC 机会升温。"
  },
  {
    id: "act-003",
    title: "Lattice Cloud 预计本周签约",
    kind: "商机更新",
    accountId: "acct-lattice",
    accountName: "Lattice Cloud",
    owner: "Alec",
    createdAt: "2026-04-25",
    summary: "采购已完成内部流转，只剩法务对数据保留时长的最后一轮确认。"
  },
  {
    id: "act-004",
    title: "Summit Motors 沉默预警触发",
    kind: "客户预警",
    accountId: "acct-summit",
    accountName: "Summit Motors",
    owner: "Mika",
    createdAt: "2026-04-24",
    summary: "连续两次会议延期且未给出新时间，需要更高层介入稳住关系。"
  },
];

export const crmPipelineStages: PipelineStageSummary[] = [
  {
    id: "线索初筛",
    name: "线索初筛",
    opportunityIds: ["opp-ripple-new"],
    totalAmount: 240000,
    winRate: 28,
  },
  {
    id: "方案沟通",
    name: "方案沟通",
    opportunityIds: ["opp-helix-poc"],
    totalAmount: 180000,
    winRate: 45,
  },
  {
    id: "商务谈判",
    name: "商务谈判",
    opportunityIds: ["opp-aurora-expand", "opp-summit-renewal"],
    totalAmount: 850000,
    winRate: 50,
  },
  {
    id: "签约推进",
    name: "签约推进",
    opportunityIds: ["opp-lattice-master"],
    totalAmount: 680000,
    winRate: 84,
  },
];

export function getCrmMetrics(): CrmMetrics {
  const openPipelineAmount = crmOpportunities.reduce((total, opportunity) => total + opportunity.amount, 0);
  const weightedForecastAmount = crmOpportunities.reduce(
    (total, opportunity) => total + opportunity.amount * (opportunity.probability / 100),
    0,
  );

  return {
    activeCustomers: crmCustomers.length,
    todayFollowUps: crmFollowUps.filter((task) => task.dueDate === "2026-04-27").length,
    openPipelineAmount,
    weightedForecastAmount,
    highRiskCustomers: crmCustomers.filter((customer) => customer.healthScore < 60).length,
  };
}
